In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
df=pd.read_csv(r"C:\Users\Prabal Kuinkel\Desktop\Data Analyst\PYTHON JUPYTERNOOTBOOK\Data sets and notes\Data sets\iris.csv")

In [16]:
#single dimensional Numpy Array
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [17]:
type(n1)

numpy.ndarray

In [20]:
#Multidimensional Numpy array
n2=np.array([[10,20,30,5,7],[10,80,90,6,2],[8,6,4,54,6],[9,1,2,3,6]])
n2

array([[10, 20, 30,  5,  7],
       [10, 80, 90,  6,  2],
       [ 8,  6,  4, 54,  6],
       [ 9,  1,  2,  3,  6]])

In [22]:
type(n2)

numpy.ndarray

In [26]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

##Initilaization a array of matrix 

In [28]:
n4=np.full((3,3),9)
n4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [33]:
#initilaization of numpy array within the range
n5=np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
#initialize of array from range 10 to 19 with interval of 2
n5=np.arange(10,20,2) 
n5

array([10, 12, 14, 16, 18])

In [41]:
#initialize numpy with random numbers(6 ota number )
n7=np.random.randint(100,1000,7)
n7

array([173, 627, 913, 805, 343, 949, 621])

In [47]:
#transpoe of matrix 
n8=np.array([[10,2,7],[4,5,6],[56,23,4],[78,3,2]])
n8

array([[10,  2,  7],
       [ 4,  5,  6],
       [56, 23,  4],
       [78,  3,  2]])

In [48]:
n8.shape

(4, 3)

In [50]:
n8.shape=(3,4)
n8

array([[10,  2,  7,  4],
       [ 5,  6, 56, 23],
       [ 4, 78,  3,  2]])